# FV Camera - Minimal Configuration
# Lightweight configuration for resource-constrained systems

fv_camera:
  ros__parameters:
    # Camera selection
    camera_selection:
      selection_method: "auto"
      device_index: 0
    
    # Power management
    power_management:
      startup_delay: 0.2
    
    # Camera settings
    camera:
      width: 320
      height: 240
      fps: 10
      brightness: -1
      contrast: -1
      saturation: -1
      hue: -1
      gain: -1
      exposure: -1
    
    # Stream settings
    streams:
      color_enabled: true
      compressed_enabled: false
    
    # Camera info and compression
    camera_info:
      enable_camera_info: false
      enable_compressed_topics: false
      compressed_quality: 85
    
    # Services
    services:
      get_camera_info_enabled: false
      set_camera_settings_enabled: false
    
    # TF settings
    tf:
      enabled: false
      base_frame: "base_link"
      camera_frame: "camera_link"
      optical_frame: "camera_optical_frame"
    
    # Topics
    topics:
      color: "image_raw"
      color_compressed: "image_raw/compressed" 