/**:
  ros__parameters:
    input_image_topic: "/fv/d405/color/image_raw"
    qos:
      reliability: "best_effort"
      queue_size: 10
    # backend: auto|tensorrt|openvino
    backend: "auto"
    # For TensorRT backend, provide .engine/.plan path.
    # For OpenVINO backend, provide .xml path.
    model_path: "/ros2_ws/models/tensorrt/yolo11n-seg.engine"
    device: "GPU"
    conf_thres: 0.25
    iou_thres: 0.5
    publish_detections: true
    publish_overlay: true
    nms_class_agnostic: true
    max_detections: 100
    debug_shapes: false
