# DJI O4 Air Unit Camera Calibration Parameters
# Based on DJI Mini 4 Pro specifications
# Image Sensor: 1/1.3-inch CMOS, 48MP
# FOV: 82.1°, Format Equivalent: 24mm, f/1.7

%YAML:1.0

image_width: 640   # Downsampled to VGA for SLAM
image_height: 480
camera_name: "dji_o4_air_unit"

# Camera matrix (intrinsic parameters)
# Scaled from 1440x1080 to 640x480 (scale factor: 4/9)
camera_matrix:
  rows: 3
  cols: 3
  data: [533.3, 0.0, 320.0,
         0.0, 533.3, 240.0,
         0.0, 0.0, 1.0]

# Distortion model
distortion_model: "plumb_bob"

# Distortion coefficients [k1, k2, t1, t2, k3]
# Conservative estimates for DJI gimbal cameras
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.1, 0.05, 0.0, 0.0, 0.0]

# Rectification matrix (identity for monocular camera)
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]

# Projection matrix
projection_matrix:
  rows: 3
  cols: 4
  data: [533.3, 0.0, 320.0, 0.0,
         0.0, 533.3, 240.0, 0.0,
         0.0, 0.0, 1.0, 0.0] 