# =============================================================================
# Fluent Vision - アスパラガス解析ノード設定ファイル (D405カメラ用)
# =============================================================================
# 
# 概要：
#   - Intel RealSense D405カメラを使用したアスパラガス品質解析システム
#   - 3D点群データと2D検出結果を統合して収穫適性を判定
#   - 長さ、真っ直ぐ度、根元位置の自動測定機能
#   - D405はD415より高精度な深度測定が可能
#
# 作者：Takashi Otsuka
# 作成日：2024年
# バージョン：1.0
#
# 使用方法：
#   ros2 run fv_aspara_analyzer fv_aspara_analyzer_node \
#       --ros-args \
#       --params-file fv_aspara_analyzer_d405.yaml \
#       -r __node:=fv_aspara_analyzer_d405
# =============================================================================

fv_aspara_analyzer_d405:
  ros__parameters:
    # ===== システム情報 =====
    camera_name: "D405"  # 画面表示用のカメラ名

    preview_panel_enabled: true            # 左側のDepth/点群プレビューを有効化
    mask_overlay_enabled: true            # 画面上の緑マスク背景を無効化

    # ===== トピック設定（D405カメラ用） =====
    
    
    # 入力トピック（Fluent Vision AIシステムから）
    detection_topic: "/fv/d405/object_detection/detections"      # YOLO検出結果
    pointcloud_topic: "/fv/d405/registered_points"               # 3D点群データ（fv_realsenseのorganized出力）
    camera_info_topic: "/fv/d405/color/camera_info"              # カラーカメラキャリブレーション情報
    depth_camera_info_topic: "/fv/d405/depth/camera_info"        # 深度カメラキャリブレーション情報
    use_color_camera_info: true              # 深度をカラーへ整列している場合はtrue（カラー内参を使用）。未整列の生深度の場合はfalse（深度内参を使用）
    camera_topic: "/fv/d405/color/image_raw"                     # カラー画像
    depth_topic: "/fv/d405/depth/image_rect_raw"                 # 深度画像
    mask_topic: "/fv/d405/segmentation_mask/image"               # セグメンテーションマスク
    imu_topic: "/livox/imu"                                      # IMUデータ（姿勢補正用）

    # 出力トピック（解析結果）
    output_filtered_pointcloud_topic: "/fv/d405/aspara_analysis/filtered_points"  # フィルタリング済み点群
    output_selected_pointcloud_topic: "/fv/d405/aspara_analysis/selected_points"   # 選択点群（生ROI）
    output_detected_all_pointcloud_topic: "/fv/d405/aspara_analysis/detected_all_points"  # 全検出ROIの結合点群
    enable_detected_all_points: false  # 重い処理のためデフォルト無効（必要時のみ有効化）
    output_marker_topic: "/fv/d405/aspara_analysis/markers"  # MarkerArray出力
    output_annotated_image_topic: "/fv/d405/aspara_analysis/result"          # 注釈付き可視化画像

    # ===== 基本処理パラメータ =====
    
    # 検出・フィルタリング設定
    min_confidence: 0.3                   # 最小検出信頼度（0.0-1.0）
    pointcloud_distance_min: 0.1           # 点群処理最小距離（10cm）
    pointcloud_distance_max: 1.5           # 点群処理最大距離（1.5m に拡大して点数確保）
    aspara_filter_distance: 0.40           # アスパラ根元からの距離窓（m）さらに点数確保
    depth_unit_m_16u: 0.0001               # 16UC1深度単位（D405は0.1mm/Unit）
    disable_filtered_fallback: true        # フィルタ結果が空でもフォールバックせず空点群を公開
    simple_z_back_cut: true                # z0から一定距離後ろを強制カット
    z_back_cut_m: 0.12                     # 背面カット距離[m]（12cm）
    filtered_points_max: 3000              # 右パネル点群の上限（0=無制限）

    # ===== 根本推定・抽出帯パラメータ（表示/抽出の安定化） =====
    band_alpha: 1.00                       # 中央帯制限を解除して点数確保
    hist_band_bottom_ratio: 0.04           # 下部帯の下側比率（4%）
    hist_band_top_ratio: 0.12              # 下部帯の上側比率（12%）
    depth_scan_preview_enabled: true       # ROI下部帯のDepthスキャン可視化を有効
    root_depth_percentile: 0.10            # z0推定のパーセンタイル（p10）
    root_use_segmentation: false           # まず色/Segを無効化（安定確認後にON）
    enable_region_recognition: false       # 色/マスクによる領域認識の使用可否（UI/抽出で利用）
    root_hsv_h_min: 0.0                    # 色フィルタ実質無効化（全許容）
    root_hsv_h_max: 360.0                  # 色フィルタ実質無効化（全許容）
    root_hsv_s_min: 0.0                    # 色フィルタ実質無効化（全許容）
    root_hsv_v_min: 0.0                    # 色フィルタ実質無効化（全許容）
    root_y_offset_ratio: 0.10              # 根本Yを矩形下端から固定する比率（5%）
    root_lateral_radius_m: 0.20           # 横半径を4cmに（しっかり中心帯に絞る）

    # ===== QoS設定（入力/出力） =====
    qos:
      input_queue_size: 10
      input_reliability: "best_effort"
      output_queue_size: 10
      output_reliability: "best_effort"

    # ===== ノイズ除去パラメータ =====
    
    # 統計的外れ値除去フィルタ
    noise_reduction_neighbors: 20          # D405でも最低限の外れ値除去
    noise_reduction_std_dev: 1.0           # ノイズ除去の標準偏差しきい値
    
    # ボクセルグリッドフィルタ（ダウンサンプリング）
    voxel_leaf_size: 0.004                 # ボクセルサイズ（4mm、速度と精度のバランス）

    # ===== アスパラガス品質評価パラメータ =====
    enable_metrics: true                  # メトリクス計算を有効化
    # 長さ校正
    length_scale: 1.0                     # 長さスケール係数（1.0=無補正）
    length_offset_m: 0.0                  # 長さオフセット[m]（0.0=無補正）
    length_clip_enable: true              # 長さの表示レンジ制限を有効化
    length_min_m: 0.08                    # 最小長さ[m]（8cm未満は無効扱い）
    length_max_m: 0.40                    # 最大長さ[m]（40cm超は無効扱い）
    
    # 収穫適性判定基準
    harvest_min_length: 0.23               # 収穫最小長さ（23cm）
    harvest_max_length: 0.50               # 収穫最大長さ（50cm）
    straightness_threshold: 0.7            # 真っ直ぐ度閾値（70%以上で収穫可能）
    straightness_kappa_ref: 0.03           # 真直度正規化の基準曲率
    enable_pca_skeleton: true              # PCAベース骨格生成を有効化
    skeleton_points_count: 9               # 骨格ポイント数（9に増加: 曲がり追従性向上）
    skeleton_method: "slice_centroid"      # 骨格生成ロジック: pca_line / iterative_local / slice_centroid
    skeleton_radius_m: 0.010               # 局所重心の窓を少し絞る
    skeleton_window_m: 0.06                # 縦方向の窓を拡大して曲がりに追従

# =============================================================================
# D405 vs D415 の違い
# =============================================================================
#
# 【D405の特徴】
# - より高精度な深度測定（±2mm精度）
# - より狭い視野角（87° vs 65°）
# - より高密度な点群データ
# - より高価格（産業用途向け）
#
# 【パラメータ調整の違い】
# - voxel_leaf_size: D405はより小さく設定可能（0.003-0.008）
# - noise_reduction_neighbors: D405はより多く設定可能（50-150）
# - pointcloud_distance_max: D405はより遠距離まで測定可能（2.5m）
# =============================================================================
#
# 【ノイズ除去の調整】
# - noise_reduction_neighbors: 点群密度が高い場合は増加（50→100）
# - noise_reduction_std_dev: ノイズが多い場合は減少（1.0→0.5）
# - voxel_leaf_size: 処理速度を上げたい場合は増加（0.005→0.01）
#
# 【品質評価の調整】
# - harvest_min_length: 市場要求に応じて調整（0.20-0.30）
# - harvest_max_length: 収穫機の制約に応じて調整（0.40-0.60）
# - straightness_threshold: 品質基準に応じて調整（0.6-0.8）
#
# 【距離設定の調整】
# - pointcloud_distance_max: カメラ設置高さに応じて調整
# - aspara_filter_distance: アスパラガス密度に応じて調整
# =============================================================================