# =============================================================================
# Fluent Vision - アスパラガス解析ノード設定ファイル (D415カメラ用)
# =============================================================================
# 
# 概要：
#   - Intel RealSense D415カメラを使用したアスパラガス品質解析システム
#   - 3D点群データと2D検出結果を統合して収穫適性を判定
#   - 長さ、真っ直ぐ度、根元位置の自動測定機能
#
# 作者：Takashi Otsuka
# 作成日：2024年
# バージョン：1.0
#
# 使用方法：
#   ros2 run fv_aspara_analyzer fv_aspara_analyzer_node \
#       --ros-args \
#       --params-file fv_aspara_analyzer_d415.yaml \
#       -r __node:=fv_aspara_analyzer_d415
# =============================================================================

/**:
  ros__parameters:
    # ===== システム情報 =====
    camera_name: "D415"  # 画面表示用のカメラ名
    
    # ===== トピック設定（D415カメラ用） =====
    
    # 入力トピック（Fluent Vision AIシステムから）
    detection_topic: "/fv/d415/object_detection/detections"      # YOLO検出結果
    pointcloud_topic: "/fv/d415/registered_points"               # 3D点群データ（fv_realsenseのorganized出力）
    camera_info_topic: "/fv/d415/color/camera_info"              # カラーカメラキャリブレーション情報
    depth_camera_info_topic: "/fv/d415/depth/camera_info"        # 深度カメラキャリブレーション情報
    use_color_camera_info: true                                  # 深度をカラーへ整列している場合はtrue（カラー内参を使用）。未整列の生深度の場合はfalse（深度内参を使用）
    camera_topic: "/fv/d415/color/image_raw"                     # カラー画像
    depth_topic: "/fv/d415/depth/image_rect_raw"                 # 深度画像
    mask_topic: "/fv/d415/segmentation_mask/image"               # セグメンテーションマスク
    imu_topic: "/livox/imu"                                      # IMUデータ（姿勢補正用）

    # 出力トピック（解析結果）
    output_filtered_pointcloud_topic: "/fv/d415/aspara_analysis/filtered_points"   # フィルタリング済み点群（中間結果）
    output_selected_pointcloud_topic: "/fv/d415/aspara_analysis/selected_points"   # 選択中アスパラ点群（最終結果）
    output_detected_all_pointcloud_topic: "/fv/d415/aspara_analysis/detected_all_points"  # 全検出ROIの結合点群
    enable_detected_all_points: false
    output_marker_topic: "/fv/d415/aspara_analysis/markers"  # MarkerArray出力
    output_annotated_image_topic: "/fv/d415/aspara_analysis/result"                # 注釈付き可視化画像

    # ===== 基本処理パラメータ =====
    
    # 検出・フィルタリング設定
    min_confidence: 0.3                    # 最小検出信頼度（0.0-1.0）
    pointcloud_distance_min: 0.05           # 点群処理最小距離（5cm）
    pointcloud_distance_max: 1.0           # 点群処理最大距離（2m）
    aspara_filter_distance: 0.35           # アスパラ根元からの距離窓（m）点数確保
    depth_unit_m_16u: 0.001                # 16UC1深度単位（D415は1mm/Unit）
    enable_pointcloud_processing: true     # ポイントクラウド処理を有効化（非同期処理でカクつき解決）
    detection_timeout_seconds: 1.5         # 検出がない場合の表示タイムアウト（秒）
    disable_filtered_fallback: true       # フィルタ結果が空でもフォールバックせず空点群を公開
    simple_z_back_cut: true               # z0から一定距離後ろを強制カット
    z_back_cut_m: 0.18                    # 背面カット距離（18cm）
    filtered_points_max: 10000            # 右パネル点群の上限（0=無制限）
    
    # ===== 根本推定・抽出帯パラメータ（表示/抽出の安定化） =====
    band_alpha: 1.0                        # 中央帯無効化（点数確保）

    hist_band_bottom_ratio: 0.04           # 下部帯の下側比率（4%）
    hist_band_top_ratio: 0.12              # 下部帯の上側比率（12%）
    root_depth_percentile: 0.10            # z0推定のパーセンタイル（p10）
    root_use_segmentation: false           # まず色/Segを無効化（安定確認後にON）
    enable_region_recognition: false       # 色/マスクによる領域認識の使用可否（UI/抽出で利用）
    left_panel_enabled: false              # 左パネル（RAW点群）
    right_panel_enabled: true              # 右パネル（FILTERED点群）
    depth_scan_preview_enabled: true       # ROI下部帯のDepthスキャン可視化を有効
    mask_overlay_enabled: false            # 画面上の緑マスク背景を無効化
    root_hsv_h_min: 35.0                   # 緑抽出HSV下限（H）
    root_hsv_h_max: 85.0                   # 緑抽出HSV上限（H）
    root_hsv_s_min: 0.25                   # 緑抽出HSV下限（S）
    root_hsv_v_min: 0.20                   # 緑抽出HSV下限（V）
    root_y_offset_ratio: 0.08              # 根本Yを矩形下端から固定する比率（5%）
    root_lateral_radius_m: 0.20           # 横半径を20cmに拡大（点数確保）

    # ===== ノイズ除去パラメータ =====
    
    # 統計的外れ値除去フィルタ
    noise_reduction_neighbors: 20          # ノイズ除去強度（近接より弱め）
    noise_reduction_std_dev: 1.0           # ノイズ除去の標準偏差しきい値
    
    # ボクセルグリッドフィルタ（ダウンサンプリング）
    voxel_leaf_size: 0.006                 # ボクセルサイズ（6mm）

    # ===== アスパラガス品質評価パラメータ =====
    enable_metrics: true                   # メトリクス計算を有効化
    length_method: "auto"                 # 長さ推定: auto/skeleton/pca
    show_pca_reference_line: true          # 直線参照の表示（既定ON）
    root_clip_enable: true                 # 根本より下を切る
    root_clip_margin_m: 0.02               # マージン（2cm）
    # 長さ校正
    length_scale: 1.0                      # 長さスケール係数（1.0=無補正）
    length_offset_m: 0.0                   # 長さオフセット[m]（0.0=無補正）
    length_clip_enable: true               # 長さの表示レンジ制限を有効化
    length_min_m: 0.08                     # 最小長さ[m]（8cm未満は無効扱い）
    length_max_m: 0.40                     # 最大長さ[m]（40cm超は無効扱い）
    
    # 収穫適性判定基準
    harvest_min_length: 0.23               # 収穫最小長さ（23cm）
    harvest_max_length: 0.50               # 収穫最大長さ（50cm）
    straightness_threshold: 0.7            # 真っ直ぐ度閾値（70%以上で収穫可能）
    straightness_kappa_ref: 0.03           # 真直度正規化の基準曲率
    cutting_target_length: 0.23            # 切断対象判定長さ（23cm以上）

    # ===== QoS設定（入力/出力） =====
    qos:
      input_queue_size: 10
      input_reliability: "best_effort"
      output_queue_size: 10
      output_reliability: "best_effort"

    # ===== 点群合成パラメータ =====
    
    # 高品質点群合成設定
    mesh_building_enabled: true             # 点群合成機能有効
    frame_history_size: 30                  # 履歴フレーム数（1秒分@30FPS）
    registration_distance_threshold: 0.02   # レジストレーション距離閾値（2cm）
    mesh_voxel_size: 0.003                 # 合成用ボクセルサイズ（3mm、高密度）
    
    # MLS平滑化パラメータ
    mls_search_radius: 0.01                 # MLS検索半径（1cm）
    mls_polynomial_order: 2                 # MLS多項式次数（2次）
    mls_upsampling_enabled: true            # アップサンプリング有効
    
    # ===== TF・rtabmapパラメータ =====
    
    # TF作成設定
    tf_enabled: true                        # TF作成機能有効
    tf_frame_prefix: "asparagus_"           # TFフレーム名プレフィックス
    tf_base_frame: "map"                    # 基準座標系
    stem_base_detection_threshold: 0.02     # 根元検出範囲（2cm）
    
    # rtabmap統合設定
    rtabmap_enabled: true                   # rtabmap統合有効
    rtabmap_add_label_service: "/rtabmap/add_label"      # ラベル追加サービス
    rtabmap_set_label_service: "/rtabmap/set_label"      # ラベル設定サービス
    rtabmap_service_timeout: 5.0            # サービスタイムアウト（秒）
    
    # 完全認識判定基準
    complete_recognition_confidence: 0.8     # 完全認識信頼度閾値
    complete_recognition_frame_count: 10     # 完全認識継続フレーム数
    complete_recognition_point_density: 100  # 必要点群密度（点/cm²）
    
    # ===== 3Dマーカー表示パラメータ =====
    
    # マーカー表示設定
    marker_enabled: true                     # 3Dマーカー表示有効
    mesh_marker_enabled: true                # メッシュマーカー有効（高品質）
    cylinder_marker_enabled: true            # 円柱マーカー有効（簡易）
    info_text_marker_enabled: true           # 情報テキストマーカー有効
    
    # マーカートピック設定
    mesh_marker_topic: "/asparagus/mesh_markers"      # メッシュマーカートピック
    cylinder_marker_topic: "/asparagus/markers"       # 円柱マーカートピック
    
    # メッシュ品質設定
    mesh_segments: 20                        # 長さ方向セグメント数
    mesh_radial_points: 8                    # 円周方向点数
    mesh_smoothing_enabled: true             # メッシュ平滑化有効
    
    # マーカー色設定（グレード別）BGR
    marker_grade_a_color: [0, 255, 0]       # A級色（緑）
    marker_grade_b_color: [0, 255, 255]     # B級色（黄）
    marker_grade_c_color: [0, 128, 255]     # C級色（オレンジ）
    marker_grade_ng_color: [128, 128, 128]  # 規格外色（グレー）
    marker_alpha: 0.8                       # マーカー透明度
    
    # テキストマーカー設定
    text_marker_size: 0.03                   # テキストサイズ（3cm）
    text_marker_offset: 0.05                 # テキスト位置オフセット（5cm上）
    text_marker_color: [255, 255, 255]      # テキスト色（白）BGR
    
    # マーカー更新設定
    marker_update_rate: 2.0                  # マーカー更新レート（Hz）
    marker_lifetime: 300.0                   # マーカー生存時間（秒、5分）
    persistent_markers: true                 # 永続マーカー有効
    
    # ===== 骨格ポイント抽出パラメータ =====
    
    # 骨格ポイント設定
    enable_pca_skeleton: true                # PCAベース骨格生成を有効化
    skeleton_enabled: true                   # 骨格ポイント抽出有効
    skeleton_points_count: 9                 # 骨格点を減らして安定化
    skeleton_method: "iterative_local"      # 骨格生成: iterative_local
    skeleton_step_m: 0.022                   # ステップ長[m]（約2.2cm：到達長=約17.6cm）
    skeleton_radius_m: 0.018                 # 近傍半径[m]（1.8cm）
    skeleton_window_m: 0.06                  # 縦方向の窓を拡大して曲がりに追従
    skeleton_extraction_method: "pca_centerline"  # 抽出手法
    
    # 骨格表示設定
    skeleton_color: [255, 0, 255]           # 骨格色（ピンク）BGR
    skeleton_line_thickness: 2               # ライン太さ（ピクセル）
    skeleton_point_radius: 3                 # ポイント円半径（ピクセル）
    skeleton_point_outline_color: [255, 255, 255]  # ポイント外枠色（白）
    skeleton_point_outline_thickness: 1      # 外枠太さ
    
    # 骨格品質計算設定
    skeleton_curvature_smoothing: 3          # 曲率計算平滑化ウィンドウサイズ
    skeleton_length_precision: 0.001        # 長さ計算精度（1mm）
    skeleton_interpolation_method: "linear"  # 補間方法（"linear", "spline"）
    
    # 骨格情報公開設定
    skeleton_topic: "/fv/d415/aspara_analysis/skeleton"  # 骨格情報トピック
    skeleton_publish_rate: 5.0               # 骨格情報公開レート（Hz）
    
    # ===== 選択中アスパラガス情報公開設定 =====
    
    # 選択中アスパラガス情報設定
    selected_asparagus_info_enabled: true    # 選択中アスパラガス情報公開有効
    selected_asparagus_topic: "/selected_asparagus_info"  # 選択中アスパラガス情報トピック
    selected_asparagus_publish_rate: 10.0    # 公開レート（Hz、リアルタイム用に高頻度）
    
    # 切断ポイント設定
    cut_point_marker_enabled: true           # 切断ポイントマーカー表示有効
    cut_point_marker_size: 0.02             # 切断ポイントマーカーサイズ（2cm）
    cut_point_marker_color: [0, 0, 255]     # 切断ポイント色（赤）BGR
    cut_point_marker_lifetime: 5.0           # マーカー生存時間（秒）
    

# =============================================================================
# パラメータ調整ガイド
# =============================================================================
#
# 【ノイズ除去の調整】
# - noise_reduction_neighbors: 点群密度が高い場合は増加（50→100）
# - noise_reduction_std_dev: ノイズが多い場合は減少（1.0→0.5）
# - voxel_leaf_size: 処理速度を上げたい場合は増加（0.005→0.01）
#
# 【品質評価の調整】
# - harvest_min_length: 市場要求に応じて調整（0.20-0.30）
# - harvest_max_length: 収穫機の制約に応じて調整（0.40-0.60）
# - straightness_threshold: 品質基準に応じて調整（0.6-0.8）
#
# 【距離設定の調整】
# - pointcloud_distance_max: カメラ設置高さに応じて調整
# - aspara_filter_distance: アスパラガス密度に応じて調整
# =============================================================================