# =============================================================================
# Fluent Vision - UNetセグメンテーション設定ファイル (D415カメラ用)
# =============================================================================
# 
# 概要：
#   - UNet深層学習モデルによるアスパラガスセグメンテーション
#   - リアルタイムでのアスパラガス領域の高精度検出
#   - 2クラス分類：背景 vs アスパラガス
#
# 作者：Takashi Otsuka
# 作成日：2024年
# バージョン：1.0
#
# モデル仕様：
#   - アーキテクチャ：UNet
#   - 入力サイズ：256x256ピクセル
#   - 出力：セグメンテーションマスク
#   - 推論デバイス：GPU（OpenVINO最適化）
# =============================================================================

/**:
  ros__parameters:
    # ===== 入力トピック設定 =====
    input_image_topic: "/fv/d415/color/image_raw"    # 入力カラー画像トピック
    
    # ===== 出力トピック設定 =====
    output_segmentation_mask_topic: "/fv/d415/segmentation_mask/image"  # セグメンテーションマスク（グレースケール）
    output_colored_mask_topic: "/fv/d415/segmentation_mask/colored"     # カラーセグメンテーションマスク
    
    # ===== 処理パラメータ =====
    processing_frequency: 10.0  # 処理頻度（Hz）- 10FPSで安定動作
    enable_visualization: true  # 可視化有効（デバッグ用）
    
    # ===== QoS設定 =====
    qos:
      queue_size: 10
      reliability: "best_effort"   # 必要に応じて "reliable"
    
    # ===== UNetモデルパラメータ =====
    model:
      type: "unet"                                    # モデルタイプ：UNet
      model_path: "/models/unet_asparagus_ch16_256_v1.0_ep20.xml"  # モデルファイルパス
      device: "GPU"                                   # 推論デバイス（GPU/CPU/MYRIAD）
      input_width: 256                               # 入力画像幅（ピクセル）
      input_height: 256                              # 入力画像高さ（ピクセル）
      confidence_threshold: 0.5                      # 信頼度閾値（0.0-1.0）
    
    # ===== クラス設定 =====
    class_names: ["Background", "Asparagus"]         # クラス名（背景、アスパラガス）
    class_colors: [0, 0, 0, 0, 255, 0]              # BGR色設定：背景=黒、アスパラガス=緑

# =============================================================================
# パラメータ調整ガイド
# =============================================================================
#
# 【処理頻度の調整】
# - processing_frequency: 10.0Hz（推奨）- リアルタイム性と精度のバランス
# - 高精度重視: 5.0Hz（処理時間増加）
# - 高速処理重視: 15.0Hz（精度低下の可能性）
#
# 【信頼度閾値の調整】
# - confidence_threshold: 0.5（推奨）- 精度と検出率のバランス
# - 高精度重視: 0.7（検出率低下）
# - 高検出率重視: 0.3（誤検出増加）
#
# 【推論デバイスの選択】
# - GPU: 高速推論（推奨）
# - CPU: 安定動作（GPU未搭載時）
# - MYRIAD: 省電力推論（Intel Neural Compute Stick）
#
# 【可視化設定】
# - enable_visualization: true（デバッグ時）
# - enable_visualization: false（本番環境時、処理負荷軽減）
# =============================================================================