# =============================================================================
# Fluent Vision - アスパラガス解析ノード設定ファイル (D415カメラ用)
# =============================================================================
# 
# 概要：
#   - Intel RealSense D415カメラを使用したアスパラガス品質解析システム
#   - 3D点群データと2D検出結果を統合して収穫適性を判定
#   - 長さ、真っ直ぐ度、根元位置の自動測定機能
#
# 作者：Takashi Otsuka
# 作成日：2024年
# バージョン：1.0
#
# 使用方法：
#   ros2 run fv_aspara_analyzer fv_aspara_analyzer_node \
#       --ros-args \
#       --params-file fv_aspara_analyzer_d415.yaml \
#       -r __node:=fv_aspara_analyzer_d415
# =============================================================================

fv_aspara_analyzer_d415:
  ros__parameters:
    # ===== トピック設定（D415カメラ用） =====
    
    # 入力トピック（Fluent Vision AIシステムから）
    detection_topic: "/fv/d415/object_detection/detections"      # YOLO検出結果
    pointcloud_topic: "/fv/d415/asparagus/points"                # 3D点群データ
    camera_info_topic: "/fv/d415/color/camera_info"              # カラーカメラキャリブレーション情報
    depth_camera_info_topic: "/fv/d415/depth/camera_info"        # 深度カメラキャリブレーション情報
    camera_topic: "/fv/d415/color/image_raw"                     # カラー画像
    depth_topic: "/fv/d415/depth/image_rect_raw"                 # 深度画像
    mask_topic: "/fv/d415/segmentation_mask/image"               # セグメンテーションマスク
    imu_topic: "/livox/imu"                                      # IMUデータ（姿勢補正用）

    # 出力トピック（解析結果）
    output_filtered_pointcloud_topic: "/fv/d415/aspara_analysis/asparagus/points"  # フィルタリング済み点群
    output_annotated_image_topic: "/fv/d415/aspara_analysis/result"          # 注釈付き可視化画像

    # ===== 基本処理パラメータ =====
    
    # 検出・フィルタリング設定
    min_confidence: 0.3                    # 最小検出信頼度（0.0-1.0）
    pointcloud_distance_min: 0.1           # 点群処理最小距離（10cm）
    pointcloud_distance_max: 2.0           # 点群処理最大距離（2m）
    aspara_filter_distance: 0.05           # アスパラガス根元からのフィルタ距離（5cm）

    # ===== ノイズ除去パラメータ =====
    
    # 統計的外れ値除去フィルタ
    noise_reduction_neighbors: 50          # 統計フィルタの近傍点数（推奨：30-100）
    noise_reduction_std_dev: 1.0           # 標準偏差倍率（推奨：0.5-2.0）
    
    # ボクセルグリッドフィルタ（ダウンサンプリング）
    voxel_leaf_size: 0.010                 # ボクセルサイズ（10mm、推奨：3-10mm）

    # ===== アスパラガス品質評価パラメータ =====
    
    # 収穫適性判定基準
    harvest_min_length: 0.23               # 収穫最小長さ（23cm）
    harvest_max_length: 0.50               # 収穫最大長さ（50cm）
    straightness_threshold: 0.7            # 真っ直ぐ度閾値（70%以上で収穫可能）
    cutting_target_length: 0.23            # 切断対象判定長さ（23cm以上）

    # ===== 点群合成パラメータ =====
    
    # 高品質点群合成設定
    mesh_building_enabled: true             # 点群合成機能有効
    frame_history_size: 30                  # 履歴フレーム数（1秒分@30FPS）
    registration_distance_threshold: 0.02   # レジストレーション距離閾値（2cm）
    mesh_voxel_size: 0.003                 # 合成用ボクセルサイズ（3mm、高密度）
    
    # MLS平滑化パラメータ
    mls_search_radius: 0.01                 # MLS検索半径（1cm）
    mls_polynomial_order: 2                 # MLS多項式次数（2次）
    mls_upsampling_enabled: true            # アップサンプリング有効
    
    # ===== TF・rtabmapパラメータ =====
    
    # TF作成設定
    tf_enabled: true                        # TF作成機能有効
    tf_frame_prefix: "asparagus_"           # TFフレーム名プレフィックス
    tf_base_frame: "map"                    # 基準座標系
    stem_base_detection_threshold: 0.02     # 根元検出範囲（2cm）
    
    # rtabmap統合設定
    rtabmap_enabled: true                   # rtabmap統合有効
    rtabmap_add_label_service: "/rtabmap/add_label"      # ラベル追加サービス
    rtabmap_set_label_service: "/rtabmap/set_label"      # ラベル設定サービス
    rtabmap_service_timeout: 5.0            # サービスタイムアウト（秒）
    
    # 完全認識判定基準
    complete_recognition_confidence: 0.8     # 完全認識信頼度閾値
    complete_recognition_frame_count: 10     # 完全認識継続フレーム数
    complete_recognition_point_density: 100  # 必要点群密度（点/cm²）
    
    # ===== 3Dマーカー表示パラメータ =====
    
    # マーカー表示設定
    marker_enabled: true                     # 3Dマーカー表示有効
    mesh_marker_enabled: true                # メッシュマーカー有効（高品質）
    cylinder_marker_enabled: true            # 円柱マーカー有効（簡易）
    info_text_marker_enabled: true           # 情報テキストマーカー有効
    
    # マーカートピック設定
    mesh_marker_topic: "/asparagus/mesh_markers"      # メッシュマーカートピック
    cylinder_marker_topic: "/asparagus/markers"       # 円柱マーカートピック
    
    # メッシュ品質設定
    mesh_segments: 20                        # 長さ方向セグメント数
    mesh_radial_points: 8                    # 円周方向点数
    mesh_smoothing_enabled: true             # メッシュ平滑化有効
    
    # マーカー色設定（グレード別）BGR
    marker_grade_a_color: [0, 255, 0]       # A級色（緑）
    marker_grade_b_color: [0, 255, 255]     # B級色（黄）
    marker_grade_c_color: [0, 128, 255]     # C級色（オレンジ）
    marker_grade_ng_color: [128, 128, 128]  # 規格外色（グレー）
    marker_alpha: 0.8                       # マーカー透明度
    
    # テキストマーカー設定
    text_marker_size: 0.03                   # テキストサイズ（3cm）
    text_marker_offset: 0.05                 # テキスト位置オフセット（5cm上）
    text_marker_color: [255, 255, 255]      # テキスト色（白）BGR
    
    # マーカー更新設定
    marker_update_rate: 2.0                  # マーカー更新レート（Hz）
    marker_lifetime: 300.0                   # マーカー生存時間（秒、5分）
    persistent_markers: true                 # 永続マーカー有効
    
    # ===== 骨格ポイント抽出パラメータ =====
    
    # 骨格ポイント設定
    skeleton_enabled: true                   # 骨格ポイント抽出有効
    skeleton_points_count: 5                 # 骨格ポイント数（5または10）
    skeleton_extraction_method: "pca_centerline"  # 抽出手法
    
    # 骨格表示設定
    skeleton_color: [255, 0, 255]           # 骨格色（ピンク）BGR
    skeleton_line_thickness: 2               # ライン太さ（ピクセル）
    skeleton_point_radius: 3                 # ポイント円半径（ピクセル）
    skeleton_point_outline_color: [255, 255, 255]  # ポイント外枠色（白）
    skeleton_point_outline_thickness: 1      # 外枠太さ
    
    # 骨格品質計算設定
    skeleton_curvature_smoothing: 3          # 曲率計算平滑化ウィンドウサイズ
    skeleton_length_precision: 0.001        # 長さ計算精度（1mm）
    skeleton_interpolation_method: "linear"  # 補間方法（"linear", "spline"）
    
    # 骨格情報公開設定
    skeleton_topic: "/fv/d415/aspara_analysis/skeleton"  # 骨格情報トピック
    skeleton_publish_rate: 5.0               # 骨格情報公開レート（Hz）
    
    # ===== 選択中アスパラガス情報公開設定 =====
    
    # 選択中アスパラガス情報設定
    selected_asparagus_info_enabled: true    # 選択中アスパラガス情報公開有効
    selected_asparagus_topic: "/selected_asparagus_info"  # 選択中アスパラガス情報トピック
    selected_asparagus_publish_rate: 10.0    # 公開レート（Hz、リアルタイム用に高頻度）
    
    # 切断ポイント設定
    cut_point_marker_enabled: true           # 切断ポイントマーカー表示有効
    cut_point_marker_size: 0.02             # 切断ポイントマーカーサイズ（2cm）
    cut_point_marker_color: [0, 0, 255]     # 切断ポイント色（赤）BGR
    cut_point_marker_lifetime: 5.0           # マーカー生存時間（秒）

# =============================================================================
# パラメータ調整ガイド
# =============================================================================
#
# 【ノイズ除去の調整】
# - noise_reduction_neighbors: 点群密度が高い場合は増加（50→100）
# - noise_reduction_std_dev: ノイズが多い場合は減少（1.0→0.5）
# - voxel_leaf_size: 処理速度を上げたい場合は増加（0.005→0.01）
#
# 【品質評価の調整】
# - harvest_min_length: 市場要求に応じて調整（0.20-0.30）
# - harvest_max_length: 収穫機の制約に応じて調整（0.40-0.60）
# - straightness_threshold: 品質基準に応じて調整（0.6-0.8）
#
# 【距離設定の調整】
# - pointcloud_distance_max: カメラ設置高さに応じて調整
# - aspara_filter_distance: アスパラガス密度に応じて調整
# =============================================================================