# D415 Object Detector Configuration
fv_object_detector_d415:
  ros__parameters:
    # Input/Output topics for D415
    input_image_topic: "/fv/d415/color/image_raw"
    output_image_topic: "/fv/d415/object_detection/annotated_image"
    output_detections_topic: "/fv/d415/object_detection/detections"
    
    # Processing parameters
    processing_frequency: 10.0  # Hz
    enable_tracking: true
    enable_visualization: true
    show_stats_on_image: true
    publish_annotated_image: true
    
    # Model configuration
    model:
      type: "yolov10"
      model_path: "/models/v2_nano_best_fp16_dynamic.xml"
      device: "GPU"
      input_width: 640
      input_height: 640
      confidence_threshold: 0.5
      nms_threshold: 0.45
      min_area: 100.0
      
    # Class names (Asparagus detection)
    class_names:
      - "Asparagus"
      - "Spear"
    
    # D415 specific settings
    camera:
      name: "D415"
      resolution: "640x480"
      fps: 15 