# FV Recorder Configuration (D415 + D405)
/**:
  ros__parameters:
    # 録画設定
    recording:
      input_topics:
        # D415 topics
        - "/fv/d415/color/image_raw"
        - "/fv/d415/depth/image_rect_raw"
        # D405 topics
        - "/fv/d405/color/image_raw"
        - "/fv/d405/depth/image_rect_raw"
      output_directory: "/recordings"
      segment_duration: 300  # 5分
      retention_days: 7      # 7日間保持
      date_format: "YYYYMMDD_HHMMSS"
      auto_recording: true  # 自動録画フラグ
      default_format: "rosbag"  # デフォルト出力フォーマット

    # 再生設定
    playback:
      output_topics:
        # D415 playback topics
        - "/fv/recorder/d415/color/image_raw"
        - "/fv/recorder/d415/depth/image_rect_raw"
        # D405 playback topics
        - "/fv/recorder/d405/color/image_raw"
        - "/fv/recorder/d405/depth/image_rect_raw"
      playback_speed: 1.0    # 1.0 = 実時間
      loop_playback: true   # ループ再生

    # パススルー設定（ソーストピック → 再生トピック転写）
    passthrough:
      enable_passthrough: true  # パススルー有効
      topic_mapping:
        # D415 mapping
        "/fv/d415/color/image_raw": "/fv/recorder/d415/color/image_raw"
        "/fv/d415/depth/image_rect_raw": "/fv/recorder/d415/depth/image_rect_raw"
        # D405 mapping  
        "/fv/d405/color/image_raw": "/fv/recorder/d405/color/image_raw"
        "/fv/d405/depth/image_rect_raw": "/fv/recorder/d405/depth/image_rect_raw"

    # 外部制御設定
    control:
      enable_topic_control: true    # トピック制御有効
      enable_service_control: true  # サービス制御有効
      control_topics:
        recording_control: "/fv/recorder/recording_control"
        recording_command: "/fv/recorder/recording_command"

    # フォーマット設定
    formats:
      supported_formats:
        - "rosbag"  # ROS2 Bag形式（.db3）
        - "json"    # JSON形式（.json）
        - "yaml"    # YAML形式（.yaml）
        - "csv"     # CSV形式（.csv）
        - "mp4"     # MP4動画形式（.mp4）
        - "avi"     # AVI動画形式（.avi）
      video_settings:
        fps: 15.0           # フレームレート
        width: 640          # 解像度
        height: 480         # 解像度
        codec: "mp4v"       # 動画コーデック

    # システム設定
    system:
      status_publish_rate: 1.0  # 状態公開頻度（Hz）
      cleanup_interval: 3600    # クリーンアップ間隔（秒）
      max_file_size_mb: 1024    # 最大ファイルサイズ（MB） 